In [1]:
import numpy as np

# Sigmoid activation function
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

# Derivative of the sigmoid function
def sigmoid_derivative(x):
    return x * (1 - x)

# Input data for AND gate
X = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])

# Output data for AND gate
y = np.array([[1], [1], [1], [1]])  # Output O1

# Set the seed for reproducibility
np.random.seed(42)

# Initialize weights and biases
input_size = 2
hidden_size = 2
output_size = 1
learning_rate = 0.05
epochs = 1000

# Initialize weights and biases for the connections
weights_AV = 2 * np.random.random((input_size, hidden_size)) - 1
biases_H = np.zeros((1, hidden_size))

weights_HW = 2 * np.random.random((hidden_size, output_size)) - 1
biases_O = np.zeros((1, output_size))

# Training the neural network
for epoch in range(epochs):
    # Forward pass
    input_layer = X
    hidden_layer_input = np.dot(input_layer, weights_AV) + biases_H
    hidden_layer_output = sigmoid(hidden_layer_input)

    output_layer_input = np.dot(hidden_layer_output, weights_HW) + biases_O
    output_layer_output = sigmoid(output_layer_input)

    # Calculate the error
    error = y - output_layer_output

    # Backward pass
    d_output = error * sigmoid_derivative(output_layer_output)
    d_hidden = d_output.dot(weights_HW.T) * sigmoid_derivative(hidden_layer_output)

    # Update weights and biases
    weights_HW += learning_rate * hidden_layer_output.T.dot(d_output)
    biases_O += learning_rate * np.sum(d_output, axis=0, keepdims=True)

    weights_AV += learning_rate * input_layer.T.dot(d_hidden)
    biases_H += learning_rate * np.sum(d_hidden, axis=0, keepdims=True)

    # Check for convergence
    if np.mean(np.abs(error)) <= 0.002:
        print(f"Converged at epoch {epoch + 1}")
        break

# Print the final weights and biases
print("Final weights (A and B to H1 and H2):")
print(weights_AV)
print("Final biases (H1 and H2):")
print(biases_H)
print("Final weights (H1 and H2 to O1):")
print(weights_HW)
print("Final biases (O1):")
print(biases_O)

# Test the trained neural network
test_input = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
hidden_layer_test = sigmoid(np.dot(test_input, weights_AV) + biases_H)
predicted_output = sigmoid(np.dot(hidden_layer_test, weights_HW) + biases_O)
print("Predicted output (O1):")
print(predicted_output)


Final weights (A and B to H1 and H2):
[[-0.28204143  0.90571103]
 [ 0.43385088  0.20378376]]
Final biases (H1 and H2):
[[-0.05630965  0.01899139]]
Final weights (H1 and H2 to O1):
[[0.4930148 ]
 [0.75929419]]
Final biases (O1):
[[2.38571437]]
Predicted output (O1):
[[0.95295823]
 [0.95689156]
 [0.95829626]
 [0.96149404]]


In [2]:
import numpy as np

# Sigmoid activation function
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

# Derivative of the sigmoid function
def sigmoid_derivative(x):
    return x * (1 - x)

# Input data for the neural network
X = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])

# Output data for the neural network (as specified)
y = np.array([[1, 0], [1, 0], [0, 1], [0, 1]])

# Set the seed for reproducibility
np.random.seed(42)

# Initialize weights and biases
input_size = 2
hidden_size = 2
output_size = 2
learning_rate = 0.05
epochs = 1000

# Initialize weights and biases for the connections
weights_AV = 2 * np.random.random((input_size, hidden_size)) - 1
biases_H = np.zeros((1, hidden_size))

weights_HW = 2 * np.random.random((hidden_size, output_size)) - 1
biases_O = np.zeros((1, output_size))

# Training the neural network
for epoch in range(epochs):
    # Forward pass
    input_layer = X
    hidden_layer_input = np.dot(input_layer, weights_AV) + biases_H
    hidden_layer_output = sigmoid(hidden_layer_input)

    output_layer_input = np.dot(hidden_layer_output, weights_HW) + biases_O
    output_layer_output = sigmoid(output_layer_input)

    # Calculate the error
    error = y - output_layer_output

    # Backward pass
    d_output = error * sigmoid_derivative(output_layer_output)
    d_hidden = d_output.dot(weights_HW.T) * sigmoid_derivative(hidden_layer_output)

    # Update weights and biases
    weights_HW += learning_rate * hidden_layer_output.T.dot(d_output)
    biases_O += learning_rate * np.sum(d_output, axis=0, keepdims=True)

    weights_AV += learning_rate * input_layer.T.dot(d_hidden)
    biases_H += learning_rate * np.sum(d_hidden, axis=0, keepdims=True)

    # Check for convergence
    if np.mean(np.abs(error)) <= 0.002:
        print(f"Converged at epoch {epoch + 1}")
        break

# Print the final weights and biases
print("Final weights (A and B to H1 and H2):")
print(weights_AV)
print("Final biases (H1 and H2):")
print(biases_H)
print("Final weights (H1 and H2 to O1 and O2):")
print(weights_HW)
print("Final biases (O1 and O2):")
print(biases_O)

# Test the trained neural network
test_input = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
hidden_layer_test = sigmoid(np.dot(test_input, weights_AV) + biases_H)
predicted_output = sigmoid(np.dot(hidden_layer_test, weights_HW) + biases_O)
print("Predicted output:")
print(predicted_output)


Final weights (A and B to H1 and H2):
[[-2.10375303  3.96190983]
 [ 0.38286602 -0.22060861]]
Final biases (H1 and H2):
[[ 0.52030698 -1.66654012]]
Final weights (H1 and H2 to O1 and O2):
[[ 1.37717272 -2.280622  ]
 [-3.52888714  3.29863049]]
Final biases (O1 and O2):
[[ 1.20429801 -0.6957057 ]]
Predicted output:
[[0.8186751  0.16769528]
 [0.84812887 0.13186159]
 [0.14589996 0.87131862]
 [0.16628104 0.84647412]]


In [3]:
import numpy as np
from sklearn.neural_network import MLPClassifier
from sklearn.model_selection import RandomizedSearchCV
import warnings
from sklearn.exceptions import ConvergenceWarning
# Define the AND gate truth table
X_and = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
y_and = np.array([0, 0, 0, 1])

# Define the XOR gate truth table
X_xor = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
y_xor = np.array([0, 1, 1, 0])

# Create a function to perform hyperparameter tuning using RandomizedSearchCV
def tune_hyperparameters(X, y):
    # Define parameter grid for MLPClassifier
    param_grid = {
        'hidden_layer_sizes': [(2,), (4,), (8,), (16,)],
        'activation': ['logistic', 'tanh', 'relu'],
        'solver': ['sgd', 'adam'],
        'alpha': [0.0001, 0.001, 0.01],
        'learning_rate': ['constant', 'adaptive']
    }

    # Instantiate MLPClassifier
    mlp = MLPClassifier(max_iter=1000, random_state=42)

    # Instantiate RandomizedSearchCV with 2 splits in cross-validation
    random_search = RandomizedSearchCV(mlp, param_distributions=param_grid, n_iter=10, cv=2, random_state=42)

    # Suppress ConvergenceWarning
    with warnings.catch_warnings():
        warnings.filterwarnings("ignore", category=ConvergenceWarning)
        # Fit RandomizedSearchCV to the training data
        random_search.fit(X, y)

    # Extract the best parameters
    best_params = random_search.best_params_

    return best_params

# Tune hyperparameters for AND gate
best_params_and = tune_hyperparameters(X_and, y_and)
print("Best Parameters for AND gate:", best_params_and)

# Tune hyperparameters for XOR gate
best_params_xor = tune_hyperparameters(X_xor, y_xor)
print("Best Parameters for XOR gate:", best_params_xor)


/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/model_selection/_split.py:737: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=2.
  warnings.warn(


Best Parameters for AND gate: {'solver': 'adam', 'learning_rate': 'constant', 'hidden_layer_sizes': (2,), 'alpha': 0.0001, 'activation': 'relu'}
Best Parameters for XOR gate: {'solver': 'adam', 'learning_rate': 'constant', 'hidden_layer_sizes': (2,), 'alpha': 0.0001, 'activation': 'relu'}


In [4]:
import pandas as pd
from sklearn.neural_network import MLPClassifier
from sklearn.model_selection import train_test_split, RandomizedSearchCV
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import StandardScaler

# Load data from Excel
data = pd.read_excel(r"C:/Users/Lenovo/OneDrive/Documents/ML Dataset.xlsx")

# Separate features and target variable
features = data.iloc[:, 0:383]
target = data.iloc[:, 384]
target = target.astype(int)
# Check unique values in target variable
print("Unique values in target variable:", target.unique())

X_train,X_test,y_train,y_test=train_test_split(features,target,test_size=0.3,random_state=42)

# Feature scaling using StandardScaler
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Print shapes and types of input data
print("X_train_scaled shape:", X_train_scaled.shape, "X_train_scaled dtype:", X_train_scaled.dtype)
print("y_train shape:", y_train.shape, "y_train dtype:", y_train.dtype)



Unique values in target variable: [0 1 2 3 4 5]
X_train_scaled shape: (788, 383) X_train_scaled dtype: float64
y_train shape: (788,) y_train dtype: int64


In [5]:
mlp_classifier = MLPClassifier(hidden_layer_sizes=(100,), max_iter=1000, random_state=42)
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Train the model
mlp_classifier.fit(X_train_scaled, y_train)

# Make predictions on the test set
y_pred = mlp_classifier.predict(X_test_scaled)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy}")

Accuracy: 0.46449704142011833


In [1]:
import pandas as pd
from sklearn.neural_network import MLPClassifier
from sklearn.model_selection import train_test_split, RandomizedSearchCV
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import StandardScaler
import warnings
from sklearn.exceptions import ConvergenceWarning

# Suppress ConvergenceWarning
with warnings.catch_warnings():
    warnings.filterwarnings("ignore", category=ConvergenceWarning)


# Load data from Excel
data = pd.read_excel(r"C:/Users/Lenovo/OneDrive/Documents/ML Dataset.xlsx")

# Separate features and target variable
features = data.iloc[:, 0:383]
target = data.iloc[:, 384]
target = target.astype(int)

X_train, X_test, y_train, y_test = train_test_split(features, target, test_size=0.3, random_state=42)

# Feature scaling using StandardScaler
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Define parameter grid for MLPClassifier
param_grid = {
    'hidden_layer_sizes': [(100,), (200,), (300,)],
    'activation': ['logistic', 'tanh', 'relu'],
    'solver': ['sgd', 'adam'],
    'alpha': [0.0001, 0.001, 0.01],
    'learning_rate': ['constant', 'adaptive']
}

# Instantiate MLPClassifier
mlp = MLPClassifier(max_iter=1000, tol=1e-4)  # Increase max_iter and set tolerance to a lower value

# Instantiate RandomizedSearchCV
random_search = RandomizedSearchCV(mlp, param_distributions=param_grid, n_iter=10, cv=3, random_state=42)

# Suppress ConvergenceWarning
with warnings.catch_warnings():
    warnings.filterwarnings("ignore", category=ConvergenceWarning)
    # Fit RandomizedSearchCV to the training data
    random_search.fit(X_train_scaled, y_train)

# Extract the best parameters
best_params = random_search.best_params_
print("Best Parameters:", best_params)

# Evaluate the model on the test data
y_pred = random_search.predict(X_test_scaled)
accuracy = accuracy_score(y_test, y_pred)
print("Test Accuracy:", accuracy)


In [2]:
pip install catboost

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 26.1/26.1 MB 351.1 kB/s eta 0:00:0000:0100:02
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 47.1/47.1 kB 501.1 kB/s eta 0:00:00a 0:00:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 15.7/15.7 MB 464.2 kB/s eta 0:00:0000:0100:01

[notice] A new release of pip is available: 23.3.2 -> 24.0
[notice] To update, run: pip3 install --upgrade pip
Note: you may need to restart the kernel to use updated packages.


In [3]:
import pandas as pd
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier
from catboost import CatBoostClassifier
from xgboost import XGBClassifier
from sklearn.naive_bayes import GaussianNB

# Load data from Excel
data = pd.read_excel(r"C:/Users/Lenovo/OneDrive/Documents/ML Dataset.xlsx")

# Separate features and target variable
features = data.iloc[:, 0:383]
target = data.iloc[:, 384]
target = target.astype(int)

X_train, X_test, y_train, y_test = train_test_split(features, target, test_size=0.3, random_state=42)

# Feature scaling using StandardScaler
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Initialize classifiers
classifiers = {
    "Support Vector Machine": SVC(),
    "Decision Tree": DecisionTreeClassifier(),
    "Random Forest": RandomForestClassifier(),
    "AdaBoost": AdaBoostClassifier(),
    "CatBoost": CatBoostClassifier(),  # Corrected import statement
    "XGBoost": XGBClassifier(),
    "Naive Bayes": GaussianNB()
}

# Train and evaluate each classifier
results = {}
for name, clf in classifiers.items():
    clf.fit(X_train_scaled, y_train)
    y_pred = clf.predict(X_test_scaled)
    accuracy = accuracy_score(y_test, y_pred)
    precision = precision_score(y_test, y_pred, average='weighted')
    recall = recall_score(y_test, y_pred, average='weighted')
    f1 = f1_score(y_test, y_pred, average='weighted')
    results[name] = {"Accuracy": accuracy, "Precision": precision, "Recall": recall, "F1 Score": f1}
# insight into the training process of the CatBoost model



Learning rate set to 0.078171
0:	learn: 1.7584492	total: 185ms	remaining: 3m 4s
1:	learn: 1.7267214	total: 265ms	remaining: 2m 12s
2:	learn: 1.6971373	total: 326ms	remaining: 1m 48s
3:	learn: 1.6630610	total: 384ms	remaining: 1m 35s
4:	learn: 1.6352196	total: 443ms	remaining: 1m 28s
5:	learn: 1.6109805	total: 500ms	remaining: 1m 22s
6:	learn: 1.5861750	total: 562ms	remaining: 1m 19s
7:	learn: 1.5649576	total: 618ms	remaining: 1m 16s
8:	learn: 1.5414864	total: 675ms	remaining: 1m 14s
9:	learn: 1.5235745	total: 732ms	remaining: 1m 12s
10:	learn: 1.5034527	total: 789ms	remaining: 1m 10s
11:	learn: 1.4859888	total: 846ms	remaining: 1m 9s
12:	learn: 1.4681919	total: 903ms	remaining: 1m 8s
13:	learn: 1.4560353	total: 961ms	remaining: 1m 7s
14:	learn: 1.4402764	total: 1.04s	remaining: 1m 8s
15:	learn: 1.4230023	total: 1.11s	remaining: 1m 8s
16:	learn: 1.4080592	total: 1.17s	remaining: 1m 7s
17:	learn: 1.3902888	total: 1.23s	remaining: 1m 7s
18:	learn: 1.3771125	total: 1.3s	remaining: 1m 7s
19

In [4]:
# Print performance metrics for each classifier

for name, metrics in results.items():
    print(f"{name}: {metrics}")

Support Vector Machine: {'Accuracy': 0.4378698224852071, 'Precision': 0.46500895276626586, 'Recall': 0.4378698224852071, 'F1 Score': 0.41662683205388784}
Decision Tree: {'Accuracy': 0.35502958579881655, 'Precision': 0.35870460610279614, 'Recall': 0.35502958579881655, 'F1 Score': 0.35595678305877754}
Random Forest: {'Accuracy': 0.45857988165680474, 'Precision': 0.4828562703220479, 'Recall': 0.45857988165680474, 'F1 Score': 0.4378710971372281}
AdaBoost: {'Accuracy': 0.29289940828402367, 'Precision': 0.2922211368892935, 'Recall': 0.29289940828402367, 'F1 Score': 0.27032330059802373}
CatBoost: {'Accuracy': 0.4822485207100592, 'Precision': 0.5014538000963341, 'Recall': 0.4822485207100592, 'F1 Score': 0.4691963896609497}
XGBoost: {'Accuracy': 0.46449704142011833, 'Precision': 0.5001951467336083, 'Recall': 0.46449704142011833, 'F1 Score': 0.4575482968752881}
Naive Bayes: {'Accuracy': 0.3343195266272189, 'Precision': 0.36341126936660434, 'Recall': 0.3343195266272189, 'F1 Score': 0.338176321296